<?php
require_once "common.php";
page_header("I Titoli Nobiliari di LoGD");
output(" `3`c`bI Titoli Nobiliari di LoGD`b`c`n`n`3");
addnav("D?Torna dal Druido","mondruido.php");
addnav("M?Torna al Monastero","monastero.php");
output(" E allora eccoti la lista completa dei Titoli Nobiliari disponibili in `2LoGD`&! `n`n");
output("`4La Lista dei Titoli`n");
output("`2Contadino, Contadina `n");
output("Esploratore, Esploratrice `n");
output("Scudiero, Scudiera `n");
output("Gladiatore, Gladiatrice `n");
output("Legionario, Legionaria `n");
output("Centurione, Centurionessa `n");
output("Sir, Madame `n");
output("Castaldo, Castalda `n");
output("Camerlengo, Camerlenga `n");
output("Maggiore, Maggiore `n");
output("`3Barone, Baronessa `n");
output("Conte, Contessa `n");
output("Visconte, Viscontessa`n");
output("Marchese, Marchesa`n");
output("Cancelliere, Cancelliere`n");
output("Principe, Principessa`n");
output("Re, Regina`n");
output("Imperatore, Imperatrice`n");
output("Angelo, Angelo `n");
output("Arcangelo, Arcangelo `n");
output("`&Principato, Principato `n");
output("Potenza, Potenza `n");
output("Virtù, Virtù `n");
output("Dominazione, Dominazione `n");
output("Trono, Trono `n");
output("Cherubino, Cherubina `n");
output("Serafino, Serafina `n");
output("Semidio, Semidea `n");
output("Titano, Titano `n");
output("Antico, Antica `n");
output("Dio Minore, Dea Minore `n");
output("`6oltre il lvl 32");
output("`bDio, Dea`b `n");
page_footer();
?>